### ISSUE TITLE
Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) 

### ISSUE THREAD

**Issue by theasteve** [slack-ruby/slack-ruby-bot-server-events-sample#6]
When running `foreman start` I get the following error stack trace:
```
09:29:59 web.1  | started with pid 34597
09:30:00 web.1  | Puma starting in single mode...
09:30:00 web.1  | * Puma version: 5.6.4 (ruby 3.0.0-p0) ("Birdie's Version")
09:30:00 web.1  | *  Min threads: 0
09:30:00 web.1  | *  Max threads: 5
09:30:00 web.1  | *  Environment: development
09:30:00 web.1  | *          PID: 34597
09:30:35 web.1  | W, [2022-05-26T09:30:02.904788 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:03.907261 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:04.909189 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:05.910196 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:06.911338 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:07.910864 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:08.911643 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:09.912407 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:10.913419 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:11.915141 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:12.916599 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:13.917654 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:14.918637 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:15.920178 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:16.921682 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:17.923136 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:18.924406 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:19.925901 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:20.927436 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:21.928206 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:22.929767 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:23.931036 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:24.932464 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:25.933702 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:26.934407 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:27.935726 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:28.935228 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:29.937025 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:30.936996 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:31.939267 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:32.940447 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:33.909469 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:34.911084 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:30:35 web.1  | W, [2022-05-26T09:30:35.911434 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | Error connecting to MongoDB: No primary server is available in cluster: #<Cluster topology=Unknown[127.0.0.1:27017] servers=[#<Server address=127.0.0.1:27017 UNKNOWN>]> with timeout=30, LT=0.015
09:31:03 web.1  | W, [2022-05-26T09:30:36.912636 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:37.914156 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:38.915677 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:39.916400 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:40.917139 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:41.919447 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:42.919412 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:43.921327 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:44.922785 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:45.922562 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:46.923599 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:47.924350 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:48.925679 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:49.927071 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:50.927101 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:51.928033 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:52.927979 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:53.929547 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:54.930273 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:55.930972 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:56.930708 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:57.931828 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:58.933072 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:30:59.935143 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:31:00.936003 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:31:01.935893 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | W, [2022-05-26T09:31:02.935886 #34597]  WARN -- : MONGODB | Error checking 127.0.0.1:27017: Mongo::Error::SocketError: Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:27017 (for 127.0.0.1:27017 (no TLS)) (on 127.0.0.1:27017)
09:31:03 web.1  | ! Unable to load application: Mongo::Error::NoServerAvailable: No primary server is available in cluster: #<Cluster topology=Unknown[127.0.0.1:27017] servers=[#<Server address=127.0.0.1:27017 UNKNOWN>]> with timeout=30, LT=0.015
09:31:03 web.1  | bundler: failed to load command: puma (/Users/stevenaguilar/.rvm/gems/ruby-3.0.0/bin/puma)
09:31:03 web.1  | /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/mongo-2.17.1/lib/mongo/server_selector/base.rb:285:in `select_server': No primary server is available in cluster: #<Cluster topology=Unknown[127.0.0.1:27017] servers=[#<Server address=127.0.0.1:27017 UNKNOWN>]> with timeout=30, LT=0.015 (Mongo::Error::NoServerAvailable)
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/mongo-2.17.1/lib/mongo/database.rb:220:in `block in command'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/mongo-2.17.1/lib/mongo/client.rb:1067:in `with_session'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/mongo-2.17.1/lib/mongo/database.rb:219:in `command'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/forwardable.rb:238:in `command'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/slack-ruby-bot-server-1.2.1/lib/slack-ruby-bot-server/config/database_adapters/mongoid.rb:9:in `check!'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/slack-ruby-bot-server-1.2.1/lib/slack-ruby-bot-server/app.rb:18:in `check_database!'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/slack-ruby-bot-server-1.2.1/lib/slack-ruby-bot-server/app.rb:6:in `prepare!'
09:31:03 web.1  | 	from config.ru:7:in `block in <main>'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/puma-5.6.4/lib/puma/configuration.rb:348:in `load_rackup'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/puma-5.6.4/lib/puma/configuration.rb:270:in `app'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/puma-5.6.4/lib/puma/runner.rb:150:in `load_and_bind'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/puma-5.6.4/lib/puma/single.rb:44:in `run'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/puma-5.6.4/lib/puma/launcher.rb:182:in `run'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/puma-5.6.4/lib/puma/cli.rb:81:in `run'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/puma-5.6.4/bin/puma:10:in `<top (required)>'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/bin/puma:23:in `load'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/bin/puma:23:in `<top (required)>'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `load'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `kernel_load'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:23:in `run'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:478:in `exec'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:31:in `dispatch'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:25:in `start'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/exe/bundle:49:in `block in <top (required)>'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/exe/bundle:37:in `<top (required)>'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `load'
09:31:03 web.1  | 	from /Users/stevenaguilar/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `<main>'
09:31:03 web.1  | exited with code 1
09:31:03 system | sending SIGTERM to all processes
```

I wonder if there is some setup missing in the documentation for MongoDB? If so I am happy to create a PR to update the docs with such information. Or maybe this is something that is on my end

**Comment by theasteve** [comment]
It seems there is no support for Ruby 3.0.0 but something is being cook for the near future: https://jira.mongodb.org/browse/RUBY-2268

Would love to update support for Ruby 3 when the mongodb adds support.

**Comment by theasteve** [comment]
Reopening since support for 3.0.0 has been done https://github.com/mongodb/mongo-ruby-driver/commit/285a693a80017a0507d810d3e94f9e136a67e7d7

**Comment by CrazyOptimist** [comment]
How did you configure mongodb connection?  
Just for a quick reference, check [here](https://github.com/CrazyOptimist/slack-rails-bot-starter/blob/master/.env.example).  
You can shoot a PR for improving the documentation once you got it working.  
Let me know if the issue persists

**Comment by theasteve** [comment]
Hi @CrazyOptimist, would you be able to guide me on how to set up these. 
https://github.com/slack-ruby/slack-ruby-bot-server-events-sample/blob/master/config/mongoid.yml#L24
Im still unable to get the app to work. I wonder if there are some issues with the mongo DB setup. 
The `.env.sample` does not have any ENV variables for the mongo db.
https://github.com/slack-ruby/slack-ruby-bot-server-events-sample/blob/master/.env.sample

**Comment by CrazyOptimist** [comment]
`MONGO_URL` doesn't work out?  
Please make sure your app is running in production mode in case you are going to use env var for mongo connection.
