### ISSUE TITLE
Grape::Exceptions::ValidationErrors: type is missing

### ISSUE THREAD

**Issue by theasteve** [slack-ruby/slack-ruby-bot-server-events-sample#7]
Thanks for your patience. I'm trying to use this project with Ruby version `3.0.1-p64`. When running `foreman start` I get the following error:
```
stevenaguilar ~/slack-ruby-bot-server-events-sample on master[!]
$ foreman start
07:47:08 web.1  | started with pid 6695
07:47:09 web.1  | Puma starting in single mode...
07:47:09 web.1  | * Puma version: 5.6.4 (ruby 3.0.1-p64) ("Birdie's Version")
07:47:09 web.1  | *  Min threads: 0
07:47:09 web.1  | *  Max threads: 5
07:47:09 web.1  | *  Environment: development
07:47:09 web.1  | *          PID: 6695
07:47:12 web.1  | * Listening on http://0.0.0.0:5000
07:47:12 web.1  | Use Ctrl-C to stop
07:52:04 web.1  | I, [2022-06-02T07:52:04.277423 #6695]  INFO -- : Starting team name=BigShort, id=TSFN24QMA.
08:15:07 web.1  | W, [2022-06-02T08:15:07.836780 #6695]  WARN -- : Grape::Exceptions::ValidationErrors: type is missing
08:15:07 web.1  |   /Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:365:in `run_validators'
08:15:07 web.1  |   /Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:259:in `block in run'
08:15:07 web.1  |   /Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.3/lib/active_support/notifications.rb:208:in `instrument'
08:15:07 web.1  |   /Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:241:in `run'
08:15:07 web.1  |   /Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:316:in `block in build_stack'
08:15:07 web.1  |   /Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/newrelic_rpm-8.7.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
```
From the stack trace I notice that the version is `grape-1.6.2`  Since this is a newly version I took a look into the gem and noticed that there are some [Upgrading Grape guidelines](https://github.com/ruby-grape/grape/blob/master/UPGRADING.md#upgrading-grape). It seems from the upgrading documentation that the type has to be declared as shown in the code snippet below:
```
params do
  requires :id, type: Integer
  group :name do
    requires :first_name
    requires :last_name
  end
end
```
However, I'm unable to track where is this being raised in the codebase for the sample app. It seems the stack trace points to the following line https://github.com/ruby-grape/grape/blob/master/lib/grape/endpoint.rb#L365 but I can't seem to find were the arguments for that method call are being passed in this codebase.

Im new to this gem, would love some sort of guidance as to where is grape being used and where could this error be raised from.
Any bit of guidance is appreciated.

**Comment by CrazyOptimist** [comment]
@dblock could you help if you have time to do?  I still haven't used it with Ruby 3, but still can look into this next week hopefully.

**Comment by theasteve** [comment]
```
stevenaguilar ~/slack-ruby-bot-server-events-sample on update-ruby-version[+!]
$ foreman start
16:49:50 web.1  | started with pid 35238
16:49:50 web.1  | Puma starting in single mode...
16:49:50 web.1  | * Puma version: 5.6.4 (ruby 3.0.1-p64) ("Birdie's Version")
16:49:50 web.1  | *  Min threads: 0
16:49:50 web.1  | *  Max threads: 5
16:49:50 web.1  | *  Environment: development
16:49:50 web.1  | *          PID: 35238
16:49:52 web.1  | 
16:49:52 web.1  | From: /Users/stevenaguilar/slack-ruby-bot-server-events-sample/lib/slash_commands/ping.rb:2 :
16:49:52 web.1  | 
16:49:52 web.1  |     1: SlackRubyBotServer::Events.configure do |config|
16:49:52 web.1  |  => 2:   binding.pry
16:49:52 web.1  |     3:   config.on :command, '/ping' do |command|
16:49:52 web.1  |     4:     puts "cookie"
16:49:52 web.1  |     5:     binding.pry
16:49:52 web.1  |     6:     command.logger.info 'Received a ping, responding with pong.'
16:49:52 web.1  |     7:     { text: 'pong' }
16:49:52 web.1  | 
[1] pry(main)> config.on :command, '/ping' do |command|
[1] pry(main)*   command.logger.info 'Received a ping, responding with pong.'
[1] pry(main)*    { text: 'pong' }
[1] pry(main)*   end
=> [#<Proc:0x00007fb0aac19ed8 (pry):1>]
```
My guess is that either ` :command, '/ping'` is missing the type or `{ text: 'pong' }` is missing the type.

**Comment by theasteve** [comment]
```
14:59:23 web.1  | From: /Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:363 Grape::Endpoint#run_validators:
14:59:23 web.1  | 
14:59:23 web.1  |     349: def run_validators(validator_factories, request)
14:59:23 web.1  |     350:   validation_errors = []
14:59:23 web.1  |     351: 
14:59:23 web.1  |     352:   validators = validator_factories.map { |options| Grape::Validations::ValidatorFactory.create_validator(**options) }
14:59:23 web.1  |     353: 
14:59:23 web.1  |     354:   ActiveSupport::Notifications.instrument('endpoint_run_validators.grape', endpoint: self, validators: validators, request: request) do
14:59:23 web.1  |     355:     validators.each do |validator|
14:59:23 web.1  |     356:       validator.validate(request)
14:59:23 web.1  |     357:     rescue Grape::Exceptions::Validation => e
14:59:23 web.1  |     358:       binding.pry
14:59:23 web.1  |     359:       validation_errors << e.stack
14:59:23 web.1  |     360:     
14:59:23 web.1  |     361:       break if validator.fail_fast?
14:59:23 web.1  |     362:     rescue Grape::Exceptions::ValidationArrayErrors => e
14:59:23 web.1  |  => 363:       binding.pry
14:59:23 web.1  |     364:       validation_errors.concat e.errors
14:59:23 web.1  |     365:       break if validator.fail_fast?
14:59:23 web.1  |     366:     end
14:59:23 web.1  |     367:   end
14:59:23 web.1  |     368: 
14:59:23 web.1  |     369:   validation_errors.any? && raise(Grape::Exceptions::ValidationErrors.new(errors: validation_errors, headers: header))
14:59:23 web.1  |     370: end
14:59:23 web.1  | 
=> ["/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/validations/validators/base.rb:61:in `validate!'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/validations/validators/base.rb:35:in `validate'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:356:in `block (2 levels) in run_validators'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:355:in `each'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:355:in `block in run_validators'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.3/lib/active_support/notifications.rb:208:in `instrument'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:354:in `run_validators'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:260:in `block in run'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.3/lib/active_support/notifications.rb:208:in `instrument'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:242:in `run'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:317:in `block in build_stack'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/newrelic_rpm-8.7.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/middleware/base.rb:36:in `call!'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/middleware/base.rb:29:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/newrelic_rpm-8.7.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/middleware/error.rb:39:in `block in call!'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/middleware/error.rb:38:in `catch'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/middleware/error.rb:38:in `call!'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/middleware/base.rb:29:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/newrelic_rpm-8.7.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/rack-2.2.3.1/lib/rack/head.rb:12:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/newrelic_rpm-8.7.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:226:in `call!'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:220:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/router/route.rb:58:in `exec'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/router.rb:120:in `process_route'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/router.rb:74:in `block in identity'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/router.rb:94:in `transaction'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/router.rb:72:in `identity'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/router.rb:56:in `block in call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/router.rb:136:in `with_optimization'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/router.rb:55:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/api/instance.rb:165:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/newrelic_rpm-8.7.0/lib/new_relic/agent/instrumentation/grape/prepend.rb:10:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/api/instance.rb:70:in `call!'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/api/instance.rb:65:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/api.rb:81:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/slack-ruby-bot-server-1.2.1/lib/slack-ruby-bot-server/api/middleware.rb:40:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/newrelic_rpm-8.7.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/rack-server-pages-0.1.0/lib/rack/server_pages.rb:46:in `serving'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/rack-server-pages-0.1.0/lib/rack/server_pages.rb:36:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/newrelic_rpm-8.7.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/newrelic_rpm-8.7.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/newrelic_rpm-8.7.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/puma-5.6.4/lib/puma/configuration.rb:252:in `call'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/puma-5.6.4/lib/puma/request.rb:77:in `block in handle_request'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/puma-5.6.4/lib/puma/thread_pool.rb:340:in `with_force_shutdown'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/puma-5.6.4/lib/puma/request.rb:76:in `handle_request'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/puma-5.6.4/lib/puma/server.rb:441:in `process_client'",
15:00:18 web.1  |  "/Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in `block in spawn_thread'"]
``` 
Im having a hard time where is the error being raised from. When I pry into the the Im still unable to determine where is the type not being declare in the codebase.

**Comment by theasteve** [comment]
Any idea on how to determine where the error is being generated from the `request` param in the following line? https://github.com/ruby-grape/grape/blob/master/lib/grape/endpoint.rb#L353 
```
15:04:09 web.1  | From: /Users/stevenaguilar/.rvm/gems/ruby-3.0.1/gems/grape-1.6.2/lib/grape/endpoint.rb:355 Grape::Endpoint#run_validators:
15:04:09 web.1  | 
15:04:09 web.1  |     349: def run_validators(validator_factories, request)
15:04:09 web.1  |     350:   validation_errors = []
15:04:09 web.1  |     351: 
15:04:09 web.1  |     352:   validators = validator_factories.map { |options| Grape::Validations::ValidatorFactory.create_validator(**options) }
15:04:09 web.1  |     353: 
15:04:09 web.1  |     354:   ActiveSupport::Notifications.instrument('endpoint_run_validators.grape', endpoint: self, validators: validators, request: request) do
15:04:09 web.1  |  => 355:     binding.pry
15:04:09 web.1  |     356:     validators.each do |validator|
15:04:09 web.1  |     357:       validator.validate(request)
15:04:09 web.1  |     358:     rescue Grape::Exceptions::Validation => e
15:04:09 web.1  |     359:       validation_errors << e.stack
15:04:09 web.1  |     360:     
15:04:09 web.1  |     361:       break if validator.fail_fast?
15:04:09 web.1  |     362:     rescue Grape::Exceptions::ValidationArrayErrors => e
15:04:09 web.1  |     363:       validation_errors.concat e.errors
15:04:09 web.1  |     364:       break if validator.fail_fast?
15:04:09 web.1  |     365:     end
15:04:09 web.1  |     366:   end
15:04:09 web.1  |     367: 
15:04:09 web.1  |     368:   validation_errors.any? && raise(Grape::Exceptions::ValidationErrors.new(errors: validation_errors, headers: header))
15:04:09 web.1  |     369: end
15:04:09 web.1  | 
[1] pry(#<#<Class:0x00007fb061e9ef30>>)> request
=> #<Grape::Request:0x00007fb05e664c78
15:04:17 web.1  |  @env=
15:04:17 web.1  |   {"rack.version"=>[1, 6],
15:04:17 web.1  |    "rack.errors"=>#<IO:<STDERR>>,
15:04:17 web.1  |    "rack.multithread"=>true,
15:04:17 web.1  |    "rack.multiprocess"=>false,
15:04:17 web.1  |    "rack.run_once"=>false,
15:04:17 web.1  |    "rack.url_scheme"=>"https",
15:04:17 web.1  |    "SCRIPT_NAME"=>"",
15:04:17 web.1  |    "QUERY_STRING"=>"",
15:04:17 web.1  |    "SERVER_PROTOCOL"=>"HTTP/1.1",
15:04:17 web.1  |    "SERVER_SOFTWARE"=>"puma 5.6.4 Birdie's Version",
15:04:17 web.1  |    "GATEWAY_INTERFACE"=>"CGI/1.2",
15:04:17 web.1  |    "REQUEST_METHOD"=>"POST",
15:04:17 web.1  |    "REQUEST_PATH"=>"/api/slack/event",
15:04:17 web.1  |    "REQUEST_URI"=>"/api/slack/event",
15:04:17 web.1  |    "HTTP_VERSION"=>"HTTP/1.1",
15:04:17 web.1  |    "HTTP_HOST"=>"776c-2603-7000-a600-5aa6-316a-9621-8ac7-4380.ngrok.io",
15:04:17 web.1  |    "HTTP_USER_AGENT"=>"Slackbot 1.0 (+https://api.slack.com/robots)",
15:04:17 web.1  |    "CONTENT_LENGTH"=>"417",
15:04:17 web.1  |    "HTTP_ACCEPT"=>"application/json,*/*",
15:04:17 web.1  |    "HTTP_ACCEPT_ENCODING"=>"gzip,deflate",
15:04:17 web.1  |    "CONTENT_TYPE"=>"application/x-www-form-urlencoded",
15:04:17 web.1  |    "HTTP_X_FORWARDED_FOR"=>"44.192.130.157",
15:04:17 web.1  |    "HTTP_X_FORWARDED_PROTO"=>"https",
15:04:17 web.1  |    "HTTP_X_SLACK_REQUEST_TIMESTAMP"=>"1654628648",
15:04:17 web.1  |    "HTTP_X_SLACK_SIGNATURE"=>"v0=1f379d740c0953a54d5d95088bb63843999ce2218d8d006aa3975bf6f840c925",
15:04:17 web.1  |    "puma.request_body_wait"=>0,
15:04:17 web.1  |    "SERVER_NAME"=>"XXXXXXXXXXX.ngrok.io",
15:04:17 web.1  |    "SERVER_PORT"=>"443",
15:04:17 web.1  |    "PATH_INFO"=>"/api/slack/event",
15:04:17 web.1  |    "REMOTE_ADDR"=>"127.0.0.1",
15:04:17 web.1  |    "puma.socket"=>#<TCPSocket:fd 21, AF_INET, 127.0.0.1, 5000>,
15:04:17 web.1  |    "rack.hijack?"=>true,
15:04:17 web.1  |    "rack.hijack"=>#<Puma::Client:0x19b4 @ready=true>,
15:04:17 web.1  |    "rack.input"=>#<StringIO:0x00007fb05e614700>,
15:04:17 web.1  |    "rack.after_reply"=>[],
15:04:17 web.1  |    "puma.config"=>
15:04:17 web.1  |     #<Puma::Configuration:0x00007fb06421e7d0
15:04:17 web.1  |      @default_dsl=
15:04:17 web.1  |       #<Puma::DSL:0x00007fb06421ce30
15:04:17 web.1  |        @config=#<Puma::Configuration:0x00007fb06421e7d0 ...>,
15:04:17 web.1  |        @options=
15:04:17 web.1  |         {:min_threads=>0,
15:04:17 web.1  |          :max_threads=>5,
15:04:17 web.1  |          :log_requests=>false,
15:04:17 web.1  |          :debug=>false,
15:04:17 web.1  |          :binds=>["tcp://0.0.0.0:9292"],
15:04:17 web.1  |          :workers=>0,
15:04:17 web.1  |          :silence_single_worker_warning=>false,
15:04:17 web.1  |          :mode=>:http,
15:04:17 web.1  |          :worker_check_interval=>5,
15:04:17 web.1  |          :worker_timeout=>60,
15:04:17 web.1  |          :worker_boot_timeout=>60,
15:04:17 web.1  |          :worker_shutdown_timeout=>30,
15:04:17 web.1  |          :worker_culling_strategy=>:youngest,
15:04:17 web.1  |          :remote_address=>:socket,
15:04:17 web.1  |          :tag=>"slack-ruby-bot-server-events-sample",
15:04:17 web.1  |          :environment=>"development",
15:04:17 web.1  |          :rackup=>"config.ru",
15:04:17 web.1  |          :logger=>#<IO:<STDOUT>>,
15:04:17 web.1  |          :persistent_timeout=>20,
15:04:17 web.1  |          :first_data_timeout=>30,
15:04:17 web.1  |          :raise_exception_on_sigterm=>true,
15:04:17 web.1  |          :max_fast_inline=>10,
15:04:17 web.1  |          :io_selector_backend=>:auto,
15:04:17 web.1  |          :mutate_stdout_and_stderr_to_sync_on_write=>true,
15:04:17 web.1  |          :preload_app=>false},
15:04:17 web.1  |        @plugins=[]>,
15:04:17 web.1  |      @file_dsl=#<Puma::DSL:0x00007fb06421cef8 @config=#<Puma::Configuration:0x00007fb06421e7d0 ...>, @options={}, @plugins=[]>,
15:04:17 web.1  |      @options=
15:04:17 web.1  |       #<Puma::UserFileDefaultOptions:0x00007fb06421d2b8
```

**Comment by theasteve** [comment]
Gemfile:
```
# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.0.1'

gem 'irb'
gem 'mongoid'
gem 'mongoid-scroll'
gem 'newrelic-slack-ruby-bot'
gem 'puma'
gem 'slack-ruby-bot-server', '>= 1.2.0'
gem 'slack-ruby-bot-server-events'
gem 'pry'

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'faker'
  gem 'rack-test'
  gem 'rake'
  gem 'rspec'
  gem 'selenium-webdriver'
  gem 'vcr'
  gem 'webmock'
end
```
This is Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    activemodel (7.0.3)
      activesupport (= 7.0.3)
    activerecord (7.0.3)
      activemodel (= 7.0.3)
      activesupport (= 7.0.3)
    activesupport (7.0.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    async (1.30.2)
      console (~> 1.10)
      nio4r (~> 2.3)
      timers (~> 4.1)
    bson (4.15.0)
    builder (3.2.4)
    capybara (3.37.1)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    coderay (1.1.3)
    concurrent-ruby (1.1.10)
    console (1.15.3)
      fiber-local
    crack (0.4.5)
      rexml
    database_cleaner (2.0.1)
      database_cleaner-active_record (~> 2.0.0)
    database_cleaner-active_record (2.0.1)
      activerecord (>= 5.a)
      database_cleaner-core (~> 2.0.0)
    database_cleaner-core (2.0.1)
    declarative (0.0.20)
    diff-lcs (1.5.0)
    dry-configurable (0.15.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 0.6)
    dry-container (0.9.0)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.13, >= 0.13.0)
    dry-core (0.7.1)
      concurrent-ruby (~> 1.0)
    dry-inflector (0.2.1)
    dry-logic (1.2.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 0.5, >= 0.5)
    dry-types (1.5.1)
      concurrent-ruby (~> 1.0)
      dry-container (~> 0.3)
      dry-core (~> 0.5, >= 0.5)
      dry-inflector (~> 0.1, >= 0.1.2)
      dry-logic (~> 1.0, >= 1.0.2)
    fabrication (2.28.0)
    faker (2.21.0)
      i18n (>= 1.8.11, < 2)
    faraday (2.3.0)
      faraday-net_http (~> 2.0)
      ruby2_keywords (>= 0.0.4)
    faraday-mashify (0.1.0)
      faraday (~> 2.0)
      hashie
    faraday-multipart (1.0.4)
      multipart-post (~> 2)
    faraday-net_http (2.0.3)
    fiber-local (1.0.0)
    foreman (0.87.2)
    gli (2.21.0)
    grape (1.6.2)
      activesupport
      builder
      dry-types (>= 1.1)
      mustermann-grape (~> 1.0.0)
      rack (>= 1.3.0)
      rack-accept
    grape-roar (0.4.1)
      grape
      multi_json
      roar (~> 1.1.0)
    grape-swagger (1.4.2)
      grape (~> 1.3)
    hashdiff (1.0.1)
    hashie (5.0.0)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    io-console (0.5.11)
    irb (1.4.1)
      reline (>= 0.3.0)
    kaminari-core (1.2.2)
    kaminari-grape (1.0.1)
      grape
      kaminari-core (~> 1.0)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    mini_portile2 (2.8.0)
    minitest (5.15.0)
    mongo (2.17.1)
      bson (>= 4.8.2, < 5.0.0)
    mongoid (7.4.0)
      activemodel (>= 5.1, < 7.1, != 7.0.0)
      mongo (>= 2.10.5, < 3.0.0)
      ruby2_keywords (~> 0.0.5)
    mongoid-compatibility (0.5.1)
      activesupport
      mongoid (>= 2.0)
    mongoid-scroll (0.3.7)
      i18n
      mongoid (>= 3.0)
      mongoid-compatibility
    multi_json (1.15.0)
    multipart-post (2.2.0)
    mustermann (1.1.1)
      ruby2_keywords (~> 0.0.1)
    mustermann-grape (1.0.2)
      mustermann (>= 1.0.0)
    newrelic-slack-ruby-bot (0.2.2)
      newrelic_rpm
      slack-ruby-bot (>= 0.10.5)
    newrelic_rpm (8.8.0)
    nio4r (2.5.8)
    nokogiri (1.13.6)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    pry (0.14.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    public_suffix (4.0.7)
    puma (5.6.4)
      nio4r (~> 2.0)
    racc (1.6.0)
    rack (2.2.3.1)
    rack-accept (0.4.5)
      rack (>= 0.4)
    rack-cors (1.1.1)
      rack (>= 2.0.0)
    rack-rewrite (1.5.1)
    rack-server-pages (0.1.0)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rake (13.0.6)
    regexp_parser (2.5.0)
    reline (0.3.1)
      io-console (~> 0.5)
    representable (3.2.0)
      declarative (< 0.1.0)
      trailblazer-option (>= 0.1.1, < 0.2.0)
      uber (< 0.2.0)
    rexml (3.2.5)
    roar (1.1.1)
      representable (~> 3.0)
    rspec (3.11.0)
      rspec-core (~> 3.11.0)
      rspec-expectations (~> 3.11.0)
      rspec-mocks (~> 3.11.0)
    rspec-core (3.11.0)
      rspec-support (~> 3.11.0)
    rspec-expectations (3.11.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.11.0)
    rspec-mocks (3.11.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.11.0)
    rspec-support (3.11.0)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    selenium-webdriver (4.2.1)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    slack-ruby-bot (0.16.1)
      activesupport
      hashie
      slack-ruby-client (>= 0.14.0)
    slack-ruby-bot-server (1.2.1)
      async
      foreman
      grape
      grape-roar (>= 0.4.0)
      grape-swagger
      kaminari-grape
      rack-cors
      rack-rewrite
      rack-server-pages
      slack-ruby-client
    slack-ruby-bot-server-events (0.3.1)
      slack-ruby-bot-server (>= 0.12.0)
    slack-ruby-client (1.1.0)
      faraday (>= 2.0)
      faraday-mashify
      faraday-multipart
      gli
      hashie
      websocket-driver
    timers (4.3.3)
    trailblazer-option (0.1.2)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    uber (0.1.0)
    vcr (6.1.0)
    webmock (3.14.0)
      addressable (>= 2.8.0)
      crack (>= 0.3.2)
      hashdiff (>= 0.4.0, < 2.0.0)
    websocket (1.2.9)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)

PLATFORMS
  ruby

DEPENDENCIES
  capybara
  database_cleaner
  fabrication
  faker
  irb
  mongoid
  mongoid-scroll
  newrelic-slack-ruby-bot
  pry
  puma
  rack-test
  rake
  rspec
  selenium-webdriver
  slack-ruby-bot-server (>= 1.2.0)
  slack-ruby-bot-server-events
  vcr
  webmock

RUBY VERSION
   ruby 3.0.1p64

BUNDLED WITH
   2.3.7
```

**Comment by theasteve** [comment]
https://github.com/theasteve/slack-app-error-showcase

**Comment by dblock** [comment]
The URL for commands should be `/api/slack/command`, not `/api/slack/event`, that's a different endpoint. Does this work?

**Comment by dblock** [comment]
I updated the documentation in https://github.com/slack-ruby/slack-ruby-bot-server-events-sample/pull/11.

**Comment by theasteve** [comment]
🤦 @dblock thanks for your help. Yes, this worked. I would love to help maintaining this projects. I will try to look into https://github.com/slack-ruby/slack-ruby-bot-server-events/issues/7
